export function parseLocaleFromPath() {
  // Get the current URL path
  const path = window.location.pathname;
  const matches = path.split('/');
  if (matches && matches[1]) {
    return matches[1];
  }
  return 'en'; // Default to English if no locale is found
}

export const consentLocales = {
  'en': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `To use DreamPip you need to accept to both our Privacy Policy and Terms of Service. <br /><br /> Our terms of service, in a nutshell, are: <br /><br />🧓 you are over 18 years; <br />📽 you can't record/download whatever is not on Mixcloud <br />`,
    bannerLinkText: '<br />Legal Page.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Do you accept?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Accept',
    rejectBtnTxt: 'Reject'
  },
  'it-it': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Per utilizzare DreamPip devi accettare sia la nostra Informativa sulla Privacy che i Termini di Servizio. <br /><br /> I nostri termini di servizio, in breve, sono: <br /><br />🧓 hai più di 18 anni; <br />📽 non puoi registrare/scaricare ciò che non è su Mixcloud <br />`,
    bannerLinkText: '<br />Pagina Legale.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Accetti?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Accetta',
    rejectBtnTxt: 'Rifiuta'
  },
  'pt-br': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Para usar o DreamPip, você precisa aceitar tanto a nossa Política de Privacidade quanto os Termos de Serviço. <br /><br /> Nossos termos de serviço, resumindo, são: <br /><br />🧓 você tem mais de 18 anos; <br />📽 você não pode gravar/baixar o que não está no Mixcloud <br />`,
    bannerLinkText: '<br />Página Legal.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Você aceita?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Aceitar',
    rejectBtnTxt: 'Rejeitar'
  },
  'es-es': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Para usar DreamPip necesitas aceptar tanto nuestra Política de Privacidad como los Términos de Servicio. <br /><br /> Nuestros términos de servicio, en resumen, son: <br /><br />🧓 tienes más de 18 años; <br />📽 no puedes grabar/descargar lo que no está en Mixcloud <br />`,
    bannerLinkText: '<br />Página Legal.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">¿Aceptas?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Aceptar',
    rejectBtnTxt: 'Rechazar'
  },
  'de-de': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Um DreamPip zu nutzen, müssen Sie sowohl unsere Datenschutzrichtlinie als auch unsere Nutzungsbedingungen akzeptieren. <br /><br /> Unsere Nutzungsbedingungen kurz gefasst sind: <br /><br />🧓 Sie sind über 18 Jahre alt; <br />📽 Sie dürfen nichts aufnehmen/herunterladen, was nicht auf Mixcloud ist <br />`,
    bannerLinkText: '<br />Rechtsseite.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Akzeptieren Sie?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Akzeptieren',
    rejectBtnTxt: 'Ablehnen'
  },
  'fr-fr': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Pour utiliser DreamPip, vous devez accepter à la fois notre Politique de Confidentialité et nos Conditions d'Utilisation. <br /><br /> Nos conditions d'utilisation, en bref, sont : <br /><br />🧓 vous avez plus de 18 ans; <br />📽 vous ne pouvez pas enregistrer/télécharger ce qui n'est pas sur Mixcloud <br />`,
    bannerLinkText: '<br />Page Légale.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Acceptez-vous?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Accepter',
    rejectBtnTxt: 'Rejeter'
  },
  'ro': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Pentru a folosi DreamPip, trebuie să accepți atât Politica noastră de Confidențialitate cât și Termenii de Serviciu. <br /><br /> Termenii noștri de serviciu, pe scurt, sunt: <br /><br />🧓 ai peste 18 ani; <br />📽 nu poți înregistra/descărca ceea ce nu este pe Mixcloud <br />`,
    bannerLinkText: '<br />Pagina Legală.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Accepți?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Acceptă',
    rejectBtnTxt: 'Respinge'
  },
  'pl-pl': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Aby korzystać z DreamPip, musisz zaakceptować zarówno naszą Politykę Prywatności, jak i Regulamin. <br /><br /> Nasz regulamin, w skrócie, mówi, że: <br /><br />🧓 masz powyżej 18 lat; <br />📽 nie możesz nagrywać/pobierać tego, czego nie ma na Mixcloud <br />`,
    bannerLinkText: '<br />Strona prawna.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Akceptujesz?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Akceptuj',
    rejectBtnTxt: 'Odrzuć'
  },
  'cs-cz': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Pro použití DreamPip musíte přijmout jak naše Zásady ochrany osobních údajů, tak i Obchodní podmínky. <br /><br /> Naše obchodní podmínky v kostce jsou: <br /><br />🧓 je vám více než 18 let; <br />📽 nemůžete nahrávat/stahovat to, co není na Mixcloud <br />`,
    bannerLinkText: '<br />Právní stránka.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Souhlasíte?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Souhlasím',
    rejectBtnTxt: 'Odmítnout'
  },
  'sv-se': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `För att använda DreamPip måste du acceptera både vår Integritetspolicy och Användarvillkor. <br /><br /> Våra användarvillkor, i korthet, är: <br /><br />🧓 du är över 18 år; <br />📽 du kan inte spela in/ladda ner det som inte finns på Mixcloud <br />`,
    bannerLinkText: '<br />Juridisk sida.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Accepterar du?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Acceptera',
    rejectBtnTxt: 'Avvisa'
  },
  'et-ee': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `DreamPip kasutamiseks peate nõustuma nii meie Privaatsuspoliitika kui ka Teenuse Tingimustega. <br /><br /> Meie teenuse tingimused lühidalt on: <br /><br />🧓 olete üle 18 aasta vana; <br />📽 te ei tohi salvestada/allalaadida seda, mis pole Mixcloudis <br />`,
    bannerLinkText: '<br />Juriidiline leht.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Kas nõustute?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Nõustu',
    rejectBtnTxt: 'Lükka tagasi'
  },
  'ja-jp': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `DreamPipを使用するには、私たちのプライバシーポリシーと利用規約の両方に同意する必要があります。<br /><br /> その利用規約の要点は以下のとおりです：<br /><br />🧓 18歳以上であること； <br />📽 Mixcloudにないものを録音/ダウンロードすることはできません <br />`,
    bannerLinkText: '<br />法的ページ。',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">同意しますか？</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: '同意する',
    rejectBtnTxt: '拒否'
  },
  'ru-ru': {
    policyLink: '/privacy',
    hideAfterClick: true,
    bannerDescription: `Для использования DreamPip вам необходимо принять нашу Политику конфиденциальности и Условия обслуживания. <br /><br /> Вкратце, наши условия обслуживания таковы: <br /><br />🧓 вам должно быть больше 18 лет; <br />📽 вы не можете записывать/скачивать то, что не находится на Mixcloud <br />`,
    bannerLinkText: '<br />Юридическая страница.',
    bannerBackground: '#1a1a1a',
    bannerColor: '#ffffff',
    bannerHeading: '<h3 style="color: white; margin-top: 0;">Вы согласны?</h3>',
    acceptBtnBackground: '#f8f8f8',
    acceptBtnColor: '#1a1a1a',
    analytics: 'UA-53455506-5',
    acceptBtnTxt: 'Принять',
    rejectBtnTxt: 'Отклонить'
  },
  'ar': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `لإستخدام DreamPip، عليك أن توافق على سياسة الخصوصية وشروط الخدمة لدينا.<br /><br />في نبذة، شروط خدمتنا:<br /><br />🧓 يجب أن تكون في الثامنة عشرة أو أكبر؛<br />📽 لا يمكنك تسجيل/تنزيل أي شيء ليس على Mixcloud<br />`,     bannerLinkText: '<br />الصفحة القانونية.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">هل توافق؟</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'وافق',     rejectBtnTxt: 'ارفض'   },
  'he': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `כדי להשתמש ב-DreamPip עליך להסכים למדיניות הפרטיות ולתנאי השימוש שלנו. <br /><br />תנאי השימוש שלנו, בקצרה, הם: <br /><br />🧓 עליך להיות מעל גיל 18; <br />📽 אינך יכול להקליט/להוריד דברים שאינם ב-Mixcloud <br />`,     bannerLinkText: '<br />עמוד משפטי.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">האם את/ה מסכים/ה?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'אשר',     rejectBtnTxt: 'דחה'   },
  'zh': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `要使用 DreamPip, 你需要同意我们的隐私政策和服务条款。 <br /><br />我们的服务条款概括为：<br /><br />🧓 你年满18岁以上;<br />📽 你不能录制/下载不在 Mixcloud 上的任何内容 <br />`,     bannerLinkText: '<br />法律页面。',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">你同意吗？</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: '同意',     rejectBtnTxt: '拒绝'   },
  'nl': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `Om DreamPip te gebruiken, moet je akkoord gaan met zowel ons Privacybeleid als onze Servicevoorwaarden. <br /><br />In een notendop zijn onze servicevoorwaarden:<br /><br />🧓 je bent ouder dan 18 jaar; <br />📽 je mag niet opnemen/downloaden wat niet op Mixcloud staat <br />`,     bannerLinkText: '<br />Juridische pagina.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Accepteer je?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Accepteren',     rejectBtnTxt: 'Weigeren'   },
  'da': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `For at bruge DreamPip skal du acceptere både vores fortrolighedspolitik og servicevilkår. <br /><br />Vores servicevilkår opsummeret: <br /><br />🧓 du er over 18 år;<br />📽 du kan ikke optage/downloade noget, der ikke er på Mixcloud <br />`,     bannerLinkText: '<br />Juridisk side.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Accepterer du?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Accepter',     rejectBtnTxt: 'Afvis'   },
  'hu': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `A DreamPip használatához el kell fogadnod az adatvédelmi szabályzatunkat és szolgáltatási feltételeinket is. <br /><br />Szolgáltatási feltételeink lényegretörően: <br /><br />🧓 18 éves vagy idősebb vagy;<br />📽 nem rögzíthetsz/letölthetsz olyan tartalmakat, amelyek nem találhatók a Mixcloud-on <br />`,     bannerLinkText: '<br />Jogi oldal.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Elfogadod?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Elfogad',     rejectBtnTxt: 'Elutasít'   },
  'ca': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `Per utilitzar DreamPip, has d'acceptar tant la nostra política de privacitat com els nostres termes de servei. <br /><br />Els nostres termes de servei, en resum, són:<br /><br />🧓 tens més de 18 anys;<br />📽 no pots enregistrar/descarregar res que no sigui a Mixcloud <br />`,     bannerLinkText: '<br />Pàgina legal.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Ho acceptes?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Accepta',     rejectBtnTxt: 'Rebutja'   },
  'eu': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `DreamPip erabiltzeko, gure Pribatutasun Politika eta Zerbitzu-aurkibideak onartu behar dituzu.<br /><br />Gure zerbitzu-baldintzak laburki: <br /><br />🧓 18 urtetik gora zauden edo;<br />📽 ezin duzu grabatu/deskargatu zeru ez dagoena Mixcloud-en <br />`,     bannerLinkText: '<br />Orri legala.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Onartzen duzu?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Onartu',     rejectBtnTxt: 'Ukatu'   },
  'gl': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `Para usar DreamPip, debes aceptar tanto nuestra Política de privacidad como nuestros Términos de servicio. <br /><br />Nuestros términos de servicio, en resumen, son: <br /><br />🧓 tienes más de 18 años;<br />📽 no puedes grabar/descargar lo que no esté en Mixcloud <br />`,     bannerLinkText: '<br />Página legal.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">¿Aceptas?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Aceptar',     rejectBtnTxt: 'Rechazar'   },
  'sw': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `Kutumia DreamPip, ni sharti ukubali Sera ya Faragha na Masharti yetu ya Huduma. <br /><br />Masharti yetu ya Huduma kwa muhtasari: <br /><br />🧓 una zaidi ya miaka 18; <br />📽 huwezi kurekodi/kupakua chochote ambacho hakipo kwenye Mixcloud <br />`,     bannerLinkText: '<br />Ukurasa wa Kisheria.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Je, unaikubali?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Kubali',     rejectBtnTxt: 'Kataa'   },
  'hi': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `DreamPip का उपयोग करने के लिए, आपको हमारी गोपनीयता नीति और सेवा की शर्तों पर सहमत होना चाहिए। <br /><br />हमारी सेवा की शर्तें संक्षेप में: <br /><br />🧓 आप 18 वर्ष से अधिक आयु के हैं;<br />📽 आप जो कुछ भी Mixcloud पर नहीं है, उसे नहीं रिकॉर्ड/डाउनलोड कर सकते <br />`,     bannerLinkText: '<br />कानूनी पेज।',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">क्या आप स्वीकार करते हैं?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'स्वीकार करें',     rejectBtnTxt: 'अस्वीकार करें'   },
  'ms': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `Untuk menggunakan DreamPip, anda perlu menerima Polisi Privasi dan Terma Perkhidmatan kami. <br /><br />Terma perkhidmatan kami, secara ringkas, adalah: <br /><br />🧓 anda berusia lebih dari 18 tahun; <br />📽 anda tidak boleh merakam/mengunduh apa-apa yang tidak berada di Mixcloud <br />`,     bannerLinkText: '<br />Halaman Undang-undang.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Adakah anda menerima?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Terima',     rejectBtnTxt: 'Tolak'   },
  'bn': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `DreamPip ব্যবহার করতে হলে আমাদের গোপনীয়তা নীতি এবং সেবা শর্তাগুলি মানতে হবে। <br /><br />সেবা শর্তাগুলি, সংক্ষেপে: <br /><br />🧓 আপনি 18 বছরের বেশি বয়সী; <br />📽 আপনি যা কিছুই Mixcloud এ নেই, তা রেকর্ড/ডাউনলোড করতে পারবেন না <br />`,     bannerLinkText: '<br />আইনি পৃষ্ঠা।',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">আপনি স্বীকার করছেন?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'প্রকাশ করুন',     rejectBtnTxt: 'প্রত্যাখ্যান করুন'   },
  'pa': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `DreamPip ਵਰਤਣ ਲਈ, ਤੁਹਾਨੂੰ ਸਾਡੀ ਨਿਜਤਾ ਧਾਰਣਾ ਅਤੇ ਸੇਵਾ ਦੀ ਨਿਯਮਾਂ ਦਾ ਸਵੀਕਾਰ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ। <br /><br />ਸਾਡੇ ਸੇਵਾ ਦੇ ਨਿਯਮ, ਇੱਕ ਵੱਖਰੇ ਦੇੜ, ਹਨ: <br /><br />🧓 ਤੁਸੀਂ 18 ਸਾਲ ਦੀ ਉਮਰ ਤੋਂ ਅੱਗੇ ਹੋ; <br />📽 ਤੁਸੀਂ ਜੋ ਕੁਝ ਵੀ Mixcloud ’ਤੇ ਨਹੀਂ ਹੈ, ਉਹ ਰਿਕਾਰਡ/ ਡਾਊਨਲੋਡ ਨਈ ਕਰ ਸਕਦੇ <br />`,     bannerLinkText: '<br />ਕਾਨੂਨੀ ਪੰਨਾ।',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">ਕੀ ਤੁਸੀਂ ਸਵੀਕਾਰ ਕਰਦੇ ਹੋ?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'ਮਨਜੂਰ ਕਰੋ',     rejectBtnTxt: 'ਇਨਕਾਰ ਕਰੋ'   },
  'tr': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `DreamPip&#39;i kullanabilmek için hem Gizlilik Politikamızı hem de Hizmet Şartlarımızı kabul etmelisiniz. <br /><br />Şartlarımızın özeti şu şekildedir: <br /><br />🧓 18 yaşınızdan büyüksünüz; <br />📽 Mixcloud'da olmayan hiçbir şeyi kaydedemez/indiremezsiniz <br />`,     bannerLinkText: '<br />Hukuki Sayfa.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Kabul ediyor musunuz?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Kabul Et',     rejectBtnTxt: 'Reddet'   },
  'fi': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `Käyttääksesi DreamPipiä, sinun tulee hyväksyä sekä yksityisyyskäytäntömme että palveluehtomme. <br /><br />Palveluehtomme tiivistettynä ovat: <br /><br />🧓 olet yli 18-vuotias; <br />📽 et voi tallentaa/ladata mitään, mitä ei ole Mixcloudissa <br />`,     bannerLinkText: '<br />Oikeudellinen sivu.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Hyväksytkö?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Hyväksy',     rejectBtnTxt: 'Hylkää'   },
  'el': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `Για να χρησιμοποιήσετε το DreamPip πρέπει να αποδεχτείτε τόσο την Πολιτική Απορρήτου όσο και τους Όρους Χρήσης μας. <br /><br />Οι όροι χρήσης μας, συνοπτικά, είναι: <br /><br />🧓 είστε άνω των 18 ετών; <br />📽 δεν μπορείτε να εγγράψετε/κατεβάσετε οτιδήποτε δεν υπάρχει στο Mixcloud <br />`,     bannerLinkText: '<br />Νομική Σελίδα.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">Αποδέχεστε;</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: 'Αποδοχη',     rejectBtnTxt: 'Απόρριψη'   },
  'ko': {     policyLink: '/privacy',     hideAfterClick: true,     bannerDescription: `DreamPip를 사용하려면 개인 정보 보호 정책과 이용 약관 모두에 동의해야 합니다. <br /><br />우리의 이용 약관은 요약하면 다음과 같습니다: <br /><br />🧓 18 세 이상이어야 합니다; <br />📽 Mixcloud에 없는 것은 녹화/다운로드할 수 없습니다 <br />`,     bannerLinkText: '<br />법적 페이지.',     bannerBackground: '#1a1a1a',     bannerColor: '#ffffff',     bannerHeading: '<h3 style="color: white; margin-top: 0;">동의하십니까?</h3>',     acceptBtnBackground: '#f8f8f8',     acceptBtnColor: '#1a1a1a',     analytics: 'UA-53455506-5',     acceptBtnTxt: '수락',     rejectBtnTxt: '거절'   },
};